// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RPGMaster.DataAccess;

#nullable disable

namespace RPGMaster.DataAccess.Migrations
{
    [DbContext(typeof(RPGMasterContext))]
    [Migration("20260820014057_Ajuste_do_Personagem")]
    partial class Ajuste_do_Personagem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("RPGMaster.Model.Arma_Detalhe", b =>
                {
                    b.Property<long>("Id_Item")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_ITEM");

                    b.Property<int>("Alcance")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ALCANCE");

                    b.Property<string>("Dano")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("DANO");

                    b.Property<int>("Tipo_Dano")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TIPO_DANO");

                    b.HasKey("Id_Item");

                    b.ToTable("ARMA_DETALHE", (string)null);
                });

            modelBuilder.Entity("RPGMaster.Model.Armadura_Detalhe", b =>
                {
                    b.Property<long>("Id_Item")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_ITEM");

                    b.Property<int>("Defesa")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DEFESA");

                    b.HasKey("Id_Item");

                    b.ToTable("ARMADURA_DETALHE", (string)null);
                });

            modelBuilder.Entity("RPGMaster.Model.Atributo", b =>
                {
                    b.Property<long>("Id_Atributo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_ATRIBUTO");

                    b.Property<long>("Id_Campanha")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_CAMPANHA");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("NOME");

                    b.Property<int>("Valor_Padrao")
                        .HasColumnType("INTEGER")
                        .HasColumnName("VALOR_PADRAO");

                    b.HasKey("Id_Atributo");

                    b.HasIndex("Id_Campanha");

                    b.ToTable("ATRIBUTO", (string)null);
                });

            modelBuilder.Entity("RPGMaster.Model.Campanha", b =>
                {
                    b.Property<long>("ID_Campanha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_CAMPANHA");

                    b.Property<long>("ID_Criador")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_CRIADOR");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("NOME");

                    b.HasKey("ID_Campanha");

                    b.HasIndex("ID_Criador");

                    b.ToTable("CAMPANHA", (string)null);
                });

            modelBuilder.Entity("RPGMaster.Model.Campanha_Jogador", b =>
                {
                    b.Property<long>("Id_Campanha")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_CAMPANHA");

                    b.Property<long>("Id_Usuario")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_USUARIO");

                    b.HasKey("Id_Campanha", "Id_Usuario");

                    b.HasIndex("Id_Usuario");

                    b.ToTable("CAMPANHA_JOGADOR", (string)null);
                });

            modelBuilder.Entity("RPGMaster.Model.Classe", b =>
                {
                    b.Property<long>("Id_Classe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_CLASSE");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT")
                        .HasColumnName("DESCRICAO");

                    b.Property<long>("Id_Campanha")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_CAMPANHA");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("NOME");

                    b.HasKey("Id_Classe");

                    b.HasIndex("Id_Campanha");

                    b.ToTable("CLASSE", (string)null);
                });

            modelBuilder.Entity("RPGMaster.Model.Classe_Atributo", b =>
                {
                    b.Property<long>("Id_Classe")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_CLASSE");

                    b.Property<long>("Id_Atributo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_ATRIBUTO");

                    b.Property<int>("Modificador")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MODIFICADOR");

                    b.HasKey("Id_Classe", "Id_Atributo");

                    b.HasIndex("Id_Atributo");

                    b.ToTable("CLASSE_ATRIBUTO", (string)null);
                });

            modelBuilder.Entity("RPGMaster.Model.Item", b =>
                {
                    b.Property<long>("Id_Item")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_ITEM");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT")
                        .HasColumnName("DESCRICAO");

                    b.Property<long>("Id_Campanha")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_CAMPANHA");

                    b.Property<string>("Imagem")
                        .HasColumnType("TEXT")
                        .HasColumnName("IMAGEM");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("NOME");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TIPO");

                    b.HasKey("Id_Item");

                    b.HasIndex("Id_Campanha");

                    b.ToTable("ITEM", (string)null);
                });

            modelBuilder.Entity("RPGMaster.Model.Item_Atributo", b =>
                {
                    b.Property<long>("Id_Item")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_ITEM");

                    b.Property<long>("Id_Atributo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_ATRIBUTO");

                    b.Property<int>("Modificador")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MODIFICADOR");

                    b.HasKey("Id_Item", "Id_Atributo");

                    b.HasIndex("Id_Atributo");

                    b.ToTable("ITEM_ATRIBUTO", (string)null);
                });

            modelBuilder.Entity("RPGMaster.Model.Magia", b =>
                {
                    b.Property<long>("Id_Magia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_MAGIA");

                    b.Property<string>("Dados")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("DADOS");

                    b.Property<long>("Id_Campanha")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_CAMPANHA");

                    b.Property<string>("Imagem")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("NOME");

                    b.HasKey("Id_Magia");

                    b.HasIndex("Id_Campanha");

                    b.ToTable("MAGIA", (string)null);
                });

            modelBuilder.Entity("RPGMaster.Model.Pericia", b =>
                {
                    b.Property<long>("Id_Pericia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_PERICIA");

                    b.Property<long>("Id_Campanha")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_CAMPANHA");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("NOME");

                    b.Property<int>("Valor_Padrao")
                        .HasColumnType("INTEGER")
                        .HasColumnName("VALOR_PADRAO");

                    b.HasKey("Id_Pericia");

                    b.HasIndex("Id_Campanha");

                    b.ToTable("PERICIA", (string)null);
                });

            modelBuilder.Entity("RPGMaster.Model.Personagem", b =>
                {
                    b.Property<long>("Id_Personagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_PERSONAGEM");

                    b.Property<bool>("EhNpc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Id_Campanha")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_CAMPANHA");

                    b.Property<long>("Id_Classe")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_CLASSE");

                    b.Property<long?>("Id_Jogador")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_JOGADOR");

                    b.Property<long>("Id_Raca")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_RACA");

                    b.Property<string>("Imagem")
                        .HasColumnType("TEXT");

                    b.Property<int>("ManaAtual")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ManaMaxima")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("NOME");

                    b.Property<int>("VidaAtual")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VidaMaxima")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id_Personagem");

                    b.HasIndex("Id_Campanha");

                    b.HasIndex("Id_Classe");

                    b.HasIndex("Id_Jogador");

                    b.HasIndex("Id_Raca");

                    b.ToTable("PERSONAGEM", (string)null);
                });

            modelBuilder.Entity("RPGMaster.Model.Personagem_Atributo", b =>
                {
                    b.Property<long>("Id_Personagem")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_PERSONAGEM");

                    b.Property<long>("Id_Atributo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_ATRIBUTO");

                    b.Property<int>("Valor")
                        .HasColumnType("INTEGER")
                        .HasColumnName("VALOR");

                    b.HasKey("Id_Personagem", "Id_Atributo");

                    b.HasIndex("Id_Atributo");

                    b.ToTable("PERSONAGEM_ATRIBUTO", (string)null);
                });

            modelBuilder.Entity("RPGMaster.Model.Personagem_Item", b =>
                {
                    b.Property<long>("Id_Personagem")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_PERSONAGEM");

                    b.Property<long>("Id_Item")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_ITEM");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER")
                        .HasColumnName("QUANTIDADE");

                    b.HasKey("Id_Personagem", "Id_Item");

                    b.HasIndex("Id_Item");

                    b.ToTable("PERSONAGEM_ITEM", (string)null);
                });

            modelBuilder.Entity("RPGMaster.Model.Personagem_Magia", b =>
                {
                    b.Property<long>("Id_Personagem")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_PERSONAGEM");

                    b.Property<long>("Id_Magia")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_MAGIA");

                    b.HasKey("Id_Personagem", "Id_Magia");

                    b.HasIndex("Id_Magia");

                    b.ToTable("PERSONAGEM_MAGIA", (string)null);
                });

            modelBuilder.Entity("RPGMaster.Model.Personagem_Pericia", b =>
                {
                    b.Property<long>("Id_Personagem")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_PERSONAGEM");

                    b.Property<long>("Id_Pericia")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_PERICIA");

                    b.Property<int>("Valor")
                        .HasColumnType("INTEGER")
                        .HasColumnName("VALOR");

                    b.HasKey("Id_Personagem", "Id_Pericia");

                    b.HasIndex("Id_Pericia");

                    b.ToTable("PERSONAGEM_PERICIA", (string)null);
                });

            modelBuilder.Entity("RPGMaster.Model.Raca", b =>
                {
                    b.Property<long>("Id_Raca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_RACA");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT")
                        .HasColumnName("DESCRICAO");

                    b.Property<long>("Id_Campanha")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_CAMPANHA");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("NOME");

                    b.HasKey("Id_Raca");

                    b.HasIndex("Id_Campanha");

                    b.ToTable("RACA", (string)null);
                });

            modelBuilder.Entity("RPGMaster.Model.Raca_Atributo", b =>
                {
                    b.Property<long>("Id_Raca")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_RACA");

                    b.Property<long>("Id_Atributo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_ATRIBUTO");

                    b.Property<int>("Modificador")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MODIFICADOR");

                    b.HasKey("Id_Raca", "Id_Atributo");

                    b.HasIndex("Id_Atributo");

                    b.ToTable("RACA_ATRIBUTO", (string)null);
                });

            modelBuilder.Entity("RPGMaster.Model.Usuario", b =>
                {
                    b.Property<long>("Id_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_USUARIO");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("CPF");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT")
                        .HasColumnName("DATA_NASC");

                    b.Property<string>("Imagem")
                        .HasColumnType("TEXT")
                        .HasColumnName("IMAGEM");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("NOME");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("SOBRENOME");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("EMAIL");

                    b.Property<string>("senha_hash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("SENHA");

                    b.Property<string>("user")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("USER");

                    b.HasKey("Id_Usuario");

                    b.ToTable("USUARIO", (string)null);
                });

            modelBuilder.Entity("RPGMaster.Model.Arma_Detalhe", b =>
                {
                    b.HasOne("RPGMaster.Model.Item", "Item")
                        .WithOne("ArmaDetalhe")
                        .HasForeignKey("RPGMaster.Model.Arma_Detalhe", "Id_Item")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("RPGMaster.Model.Armadura_Detalhe", b =>
                {
                    b.HasOne("RPGMaster.Model.Item", "Item")
                        .WithOne("ArmaduraDetalhe")
                        .HasForeignKey("RPGMaster.Model.Armadura_Detalhe", "Id_Item")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("RPGMaster.Model.Atributo", b =>
                {
                    b.HasOne("RPGMaster.Model.Campanha", "Campanha")
                        .WithMany()
                        .HasForeignKey("Id_Campanha")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campanha");
                });

            modelBuilder.Entity("RPGMaster.Model.Campanha", b =>
                {
                    b.HasOne("RPGMaster.Model.Usuario", "Criador")
                        .WithMany("CampanhasCriadas")
                        .HasForeignKey("ID_Criador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Criador");
                });

            modelBuilder.Entity("RPGMaster.Model.Campanha_Jogador", b =>
                {
                    b.HasOne("RPGMaster.Model.Campanha", "Campanha")
                        .WithMany("CampanhaJogadores")
                        .HasForeignKey("Id_Campanha")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RPGMaster.Model.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Id_Usuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campanha");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RPGMaster.Model.Classe", b =>
                {
                    b.HasOne("RPGMaster.Model.Campanha", "Campanha")
                        .WithMany()
                        .HasForeignKey("Id_Campanha")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campanha");
                });

            modelBuilder.Entity("RPGMaster.Model.Classe_Atributo", b =>
                {
                    b.HasOne("RPGMaster.Model.Atributo", "Atributo")
                        .WithMany()
                        .HasForeignKey("Id_Atributo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RPGMaster.Model.Classe", "Classe")
                        .WithMany("ClasseAtributos")
                        .HasForeignKey("Id_Classe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atributo");

                    b.Navigation("Classe");
                });

            modelBuilder.Entity("RPGMaster.Model.Item", b =>
                {
                    b.HasOne("RPGMaster.Model.Campanha", "Campanha")
                        .WithMany()
                        .HasForeignKey("Id_Campanha")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campanha");
                });

            modelBuilder.Entity("RPGMaster.Model.Item_Atributo", b =>
                {
                    b.HasOne("RPGMaster.Model.Atributo", "Atributo")
                        .WithMany()
                        .HasForeignKey("Id_Atributo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RPGMaster.Model.Item", "Item")
                        .WithMany("ItemAtributos")
                        .HasForeignKey("Id_Item")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atributo");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("RPGMaster.Model.Magia", b =>
                {
                    b.HasOne("RPGMaster.Model.Campanha", "Campanha")
                        .WithMany()
                        .HasForeignKey("Id_Campanha")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campanha");
                });

            modelBuilder.Entity("RPGMaster.Model.Pericia", b =>
                {
                    b.HasOne("RPGMaster.Model.Campanha", "Campanha")
                        .WithMany()
                        .HasForeignKey("Id_Campanha")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campanha");
                });

            modelBuilder.Entity("RPGMaster.Model.Personagem", b =>
                {
                    b.HasOne("RPGMaster.Model.Campanha", "Campanha")
                        .WithMany("Personagens")
                        .HasForeignKey("Id_Campanha")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RPGMaster.Model.Classe", "Classe")
                        .WithMany()
                        .HasForeignKey("Id_Classe")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RPGMaster.Model.Usuario", "Jogador")
                        .WithMany()
                        .HasForeignKey("Id_Jogador")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RPGMaster.Model.Raca", "Raca")
                        .WithMany()
                        .HasForeignKey("Id_Raca")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campanha");

                    b.Navigation("Classe");

                    b.Navigation("Jogador");

                    b.Navigation("Raca");
                });

            modelBuilder.Entity("RPGMaster.Model.Personagem_Atributo", b =>
                {
                    b.HasOne("RPGMaster.Model.Atributo", "Atributo")
                        .WithMany()
                        .HasForeignKey("Id_Atributo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RPGMaster.Model.Personagem", "Personagem")
                        .WithMany("Atributos")
                        .HasForeignKey("Id_Personagem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atributo");

                    b.Navigation("Personagem");
                });

            modelBuilder.Entity("RPGMaster.Model.Personagem_Item", b =>
                {
                    b.HasOne("RPGMaster.Model.Item", "Item")
                        .WithMany()
                        .HasForeignKey("Id_Item")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RPGMaster.Model.Personagem", "Personagem")
                        .WithMany("Itens")
                        .HasForeignKey("Id_Personagem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Personagem");
                });

            modelBuilder.Entity("RPGMaster.Model.Personagem_Magia", b =>
                {
                    b.HasOne("RPGMaster.Model.Magia", "Magia")
                        .WithMany()
                        .HasForeignKey("Id_Magia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RPGMaster.Model.Personagem", "Personagem")
                        .WithMany("Magias")
                        .HasForeignKey("Id_Personagem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Magia");

                    b.Navigation("Personagem");
                });

            modelBuilder.Entity("RPGMaster.Model.Personagem_Pericia", b =>
                {
                    b.HasOne("RPGMaster.Model.Pericia", "Pericia")
                        .WithMany()
                        .HasForeignKey("Id_Pericia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RPGMaster.Model.Personagem", "Personagem")
                        .WithMany("Pericias")
                        .HasForeignKey("Id_Personagem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pericia");

                    b.Navigation("Personagem");
                });

            modelBuilder.Entity("RPGMaster.Model.Raca", b =>
                {
                    b.HasOne("RPGMaster.Model.Campanha", "Campanha")
                        .WithMany()
                        .HasForeignKey("Id_Campanha")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campanha");
                });

            modelBuilder.Entity("RPGMaster.Model.Raca_Atributo", b =>
                {
                    b.HasOne("RPGMaster.Model.Atributo", "Atributo")
                        .WithMany()
                        .HasForeignKey("Id_Atributo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RPGMaster.Model.Raca", "Raca")
                        .WithMany("RacaAtributos")
                        .HasForeignKey("Id_Raca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atributo");

                    b.Navigation("Raca");
                });

            modelBuilder.Entity("RPGMaster.Model.Campanha", b =>
                {
                    b.Navigation("CampanhaJogadores");

                    b.Navigation("Personagens");
                });

            modelBuilder.Entity("RPGMaster.Model.Classe", b =>
                {
                    b.Navigation("ClasseAtributos");
                });

            modelBuilder.Entity("RPGMaster.Model.Item", b =>
                {
                    b.Navigation("ArmaDetalhe");

                    b.Navigation("ArmaduraDetalhe");

                    b.Navigation("ItemAtributos");
                });

            modelBuilder.Entity("RPGMaster.Model.Personagem", b =>
                {
                    b.Navigation("Atributos");

                    b.Navigation("Itens");

                    b.Navigation("Magias");

                    b.Navigation("Pericias");
                });

            modelBuilder.Entity("RPGMaster.Model.Raca", b =>
                {
                    b.Navigation("RacaAtributos");
                });

            modelBuilder.Entity("RPGMaster.Model.Usuario", b =>
                {
                    b.Navigation("CampanhasCriadas");
                });
#pragma warning restore 612, 618
        }
    }
}
